defaults:
  - task: wholepop
  - model: base_rnn
  - filepaths: filepaths
  - _self_

day: 2025-02-17
time: 16-19-12
job_num: 0
noise_scale: 0.5
n_inits: 1000

fpf_hps:
  max_iters: 5000
  verbose: True
  super_verbose: True
  do_compute_jacobians: False
  do_decompose_jacobians: False

hydra:
  job:
    chdir: True
  run:
    dir: ${filepaths.models}/${...day}/${...time}
  sweep:
    dir: ${filepaths.models}/${...day}/${...time}
    subdir: ${...job_num}